variable "region" {}
variable "cloudrock_project2" {}
variable "cloudrock-vpc" {}
variable "instance_tenancy" {}
variable "web-public-subnet1-cidr_block" {}
variable "web-public-subnet2-cidr_block" {}
variable "app-private-subnet1-cidr_block" {}
variable "app-private-subnet2-cidr_block" {}
variable "cloudrock-sg1" {}
variable "cloudrock-sg2" {}
variable "cloudrock-sg3" {}
variable "aws_instance-server1" {}
variable "instance_count" {}
variable "instance_type1" {}
variable "aws_instance-web1" {}
variable "instance1_count" {}
variable "instance_type2" {}
variable "aws_security_group-cloudrock-sg4" {}
variable "aws_db_subnet_group-database-subnet-group" {}
variable "cloud-database-instance-class" {}
variable "cloud-rds-instance-identifier" {}

