# Configure the AWS Provider
region                                      = "eu-west-2"
cloudrock_project2                          = "Tenacity"              
cloudrock-vpc                               = "10.0.0.0/16"
instance_tenancy                            = "default" 
web-public-subnet1-cidr_block               = "10.0.1.0/24" 
web-public-subnet2-cidr_block               = "10.0.2.0/24" 
app-private-subnet1-cidr_block              = "10.0.3.0/24" 
app-private-subnet2-cidr_block              = "10.0.4.0/24" 
cloudrock-sg1                               = "Allow HTTP and SSH traffic via Terraform 80" 
cloudrock-sg2                               = "Allow HTTP and SSH traffic via Terraform 22" 
cloudrock-sg3                               = "Allow HTTP and SSH traffic via Terraform 0"
aws_instance-server1                        = "ami-0d09654d0a20d3ae2"
instance_count                              = "2"
instance_type1                              = "t2.micro" 
aws_instance-web1                           = "ami-0d09654d0a20d3ae2" 
instance1_count                             = "2" 
instance_type2                              = "t2.micro" 
aws_security_group-cloudrock-sg4            = "enable mysql access on port 3306" 
aws_db_subnet_group-database-subnet-group   = "mysql-database-subnet" 
cloud-database-instance-class               = "db.t3.micro" 
cloud-rds-instance-identifier               = "cloud-rds-instance" 

